# Generated by Django 3.2.9 on 2021-11-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0005_usergroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
