# Generated by Django 3.2.9 on 2021-11-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0006_delete_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
    ]
