# Generated by Django 3.2.9 on 2021-11-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0007_profile_is_contractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_contractor',
        ),
    ]
