# Generated by Django 3.2.9 on 2021-11-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0008_remove_profile_is_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.BooleanField(default=False),
        ),
    ]
