# Generated by Django 3.2.9 on 2021-11-30 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0009_profile_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_type',
            new_name='is_a_company',
        ),
    ]
