# Generated by Django 3.2.9 on 2021-12-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0010_rename_user_type_profile_is_a_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_a_company',
        ),
    ]
