# Generated by Django 3.2.9 on 2021-12-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0012_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110)),
                ('description', models.TextField()),
                ('work_duties', models.TextField()),
                ('preferred_certifications', models.TextField()),
                ('minimum_qualifications', models.TextField()),
            ],
        ),
    ]
