# Generated by Django 3.2.9 on 2021-12-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0015_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=models.IntegerField(default=0), max_length=220, unique=True),
        ),
    ]
