# Generated by Django 3.2.9 on 2021-12-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0017_auto_20211223_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=models.IntegerField(default=1), max_length=220, unique=True),
        ),
    ]
