# Generated by Django 3.2.9 on 2021-12-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0019_auto_20211224_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(default=None, max_length=110, null=True, unique=True),
        ),
    ]
