# Generated by Django 3.2.9 on 2021-12-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0020_alter_job_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
    ]
