# Generated by Django 3.2.9 on 2022-01-12 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ContractorApp', '0024_alter_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
