# Generated by Django 3.2.9 on 2022-01-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0025_job_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
