# Generated by Django 3.2.9 on 2022-01-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0026_job_employer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer_email',
        ),
    ]
