# Generated by Django 3.2.9 on 2022-01-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0027_remove_job_employer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer_id_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
