# Generated by Django 3.2.9 on 2022-01-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0028_job_employer_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employer_id_number',
        ),
    ]
