# Generated by Django 3.2.9 on 2022-01-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0029_remove_job_employer_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contractors_applied',
            field=models.TextField(null=True),
        ),
    ]
