# Generated by Django 3.2.9 on 2022-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0030_job_contractors_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='contractors_applied',
            new_name='contractor_experience',
        ),
        migrations.AddField(
            model_name='job',
            name='contractor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contractor_name',
            field=models.CharField(default='', max_length=175),
        ),
    ]
