# Generated by Django 3.2.9 on 2022-01-18 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0031_auto_20220117_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='get_latest_by',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
