# Generated by Django 3.2.9 on 2022-01-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0032_job_get_latest_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='get_latest_by',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
