# Generated by Django 3.2.9 on 2022-01-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0034_auto_20220123_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='user_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
