# Generated by Django 3.2.9 on 2022-02-11 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ContractorApp', '0035_contractor_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='user_slug',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='contractor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='contractor_experience',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='contractor_name',
            field=models.CharField(default='', max_length=175),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='employer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='minimum_qualifications',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='preferred_certifications',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='title',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='work_duties',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newhiree',
            name='contractor_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='newhiree',
            name='contractor_experience',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newhiree',
            name='contractor_name',
            field=models.CharField(default='', max_length=175),
        ),
        migrations.AddField(
            model_name='newhiree',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newhiree',
            name='employer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newhiree',
            name='minimum_qualifications',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newhiree',
            name='preferred_certifications',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newhiree',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='newhiree',
            name='title',
            field=models.CharField(max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='newhiree',
            name='work_duties',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
