# Generated by Django 3.2.9 on 2022-04-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0040_remove_jobapplication_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='contractor_email',
        ),
        migrations.AddField(
            model_name='job',
            name='chosen_contractor_experience',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='chosen_contractor_name',
            field=models.CharField(default='', max_length=175),
        ),
    ]
