# Generated by Django 3.2.9 on 2022-04-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0041_auto_20220409_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='chosen_contractor_experience',
        ),
    ]
