# Generated by Django 3.2.9 on 2025-12-24 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorApp', '0042_remove_job_chosen_contractor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contractor_experience',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='minimum_qualifications',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='preferred_certifications',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_duties',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='related_experience',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='securityreport',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='securityreport',
            name='explanation',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='securityreport',
            name='steps_to_reproduce',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
